In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'name':['Sagor','Shuvo','Menoti','Endrojit','Prionty']})
df

       name
0     Sagor
1     Shuvo
2    Menoti
3  Endrojit
4   Prionty

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['en_name']=le.fit_transform(df['name'])
df

       name  en_name
0     Sagor        3
1     Shuvo        4
2    Menoti        1
3  Endrojit        0
4   Prionty        2

In [8]:
dataset = pd.read_csv('loan_application.csv')
dataset.head(23)

,Load_ID,Name,Gender,Married,Dependent,Education,Self_Employed,Application_No,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP100000,Applicant_0,Male,Yes,1,Not Graduate,No,APP1000,6392.0,7598.0,394.0,180.0,1.0,Urban,Y
1,LP100001,Applicant_1,Male,Yes,3+,Graduate,Yes,APP1001,10690.0,NaN,329.0,240.0,0.0,Rural,Y
2,LP100002,Applicant_2,Female,Yes,1,Graduate,Yes,APP1002,2521.0,2271.0,118.0,360.0,NaN,Rural,N
3,LP100003,Applicant_3,Male,Yes,1,NaN,Yes,APP1003,12613.0,14322.0,630.0,360.0,NaN,Urban,Y
4,LP100004,Applicant_4,Male,No,2,Not Graduate,No,APP1004,13795.0,NaN,593.0,NaN,NaN,NaN,N
5,LP100005,Applicant_5,Male,Yes,NaN,Not Graduate,Yes,APP1005,22029.0,6641.0,536.0,360.0,0.0,Rural,NaN
6,LP100006,Applicant_6,Male,Yes,3+,Graduate,Yes,APP1006,NaN,3030.0,487.0,120.0,0.0,Urban,N
7,LP100007,Applicant_7,Male,Yes,0,Not Graduate,Yes,APP1007,6938.0,12941.0,264.0,NaN,1.0,Urban,N
8,LP100008,Applicant_8,Female,Yes,NaN,NaN,No,APP1008,20209.0,14279.0,405.0,180.0,0.0,Rural,Y
9,LP100009,Applicant_9,Male,NaN,3+,Not Graduate,No,APP1009,21347.0,6068.0,128.0,240.0,0.0,Rural,N
10,LP100010,Applicant_10,NaN,Yes,1,Graduate,Yes,APP1010,14265.0,NaN,359.0,360.0,1.0,Semiurban,N
11,LP100011,Applicant_11,Male,Yes,3+,Graduate,Yes,APP1011,7640.0,7607.0,566.0,120.0,1.0,Urban,Y
12,LP100012,Applicant_12,Male,No,1,Graduate,No,APP1012,21003.0,11532.0,357.0,240.0,1.0,Rural,N
13,LP100013,Applicant_13,Male,Yes,2,Not Graduate,NaN,APP1013,5328.0,10377.0,493.0,360.0,1.0,Rural,N
14,LP100014,Applicant_14,Male,Yes,NaN,NaN,NaN,APP1014,11601.0,22.0,602.0,240.0,0.0,Rural,Y
15,LP100015,Applicant_15,Male,No,2,Graduate,Yes,APP1015,24610.0,14096.0,370.0,360.0,1.0,Semiurban,Y
16,LP100016,Applicant_16,Female,Yes,0,Not Graduate,No,APP1016,11805.0,10277.0,254.0,120.0,NaN,Semiurban,N
17,LP100017,Applicant_17,Male,Yes,3+,Not Graduate,No,APP1017,24760.0,1158.0,474.0,240.0,NaN,NaN,N
18,LP100018,Applicant_18,Female,No,2,Not Graduate,Yes,APP1018,2536.0,6305.0,461.0,180.0,1.0,Urban,N
19,LP100019,Applicant_19,Female,Yes,0,Not Graduate,Yes,APP1019,10396.0,14638.0,307.0,240.0,0.0,Urban,N
20,LP100020,Applicant_20,Male,Yes,1,Graduate,No,APP1020,15061.0,11317.0,689.0,360.0,1.0,Urban,N
21,LP100021,Applicant_21,Male,Yes,0,Graduate,Yes,APP1021,4344.0,5454.0,577.0,NaN,0.0,NaN,N
22,LP100022,Applicant_22,Female,Yes,2,Graduate,No,APP1022,NaN,NaN,514.0,240.0,1.0,Urban,NaN

In [19]:
dataset['Property_Area'].unique()

array(['Urban', 'Rural', nan, 'Semiurban'], dtype=object)

In [9]:
la = LabelEncoder()
la.fit(dataset['Property_Area'])

LabelEncoder()

In [18]:
la.transform(dataset['Property_Area'])

array([2, 0, 0, 2, 3, 0, 2, 2, 0, 0, 1, 2, 0, 0, 0, 1, 1, 3, 2, 2, 2, 3,
       2, 3, 0, 2, 0, 0, 2, 0, 0, 1, 0, 3, 1, 3, 0, 2, 0, 3, 2, 1, 2, 0,
       2, 1, 2, 0, 1, 2, 1, 0, 2, 0, 0, 0, 2, 2, 2, 2, 1, 0, 0, 0, 1, 2,
       2, 2, 2, 0, 0, 2, 0, 1, 3, 0, 1, 2, 1, 0, 2, 2, 2, 0, 0, 0, 2, 2,
       0, 0, 0, 0, 1, 1, 2, 1, 0, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1, 1, 1, 1,
       2, 0, 1, 1, 1, 1, 1, 0, 2, 2, 0, 2, 0, 0, 2, 1, 0, 0, 1, 1, 2, 0,
       2, 1, 0, 3, 1, 2, 2, 2, 1, 2, 3, 1, 1, 2, 1, 0, 2, 0, 2, 2, 3, 1,
       2, 0, 0, 2, 0, 0, 1, 2, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 2,
       0, 0, 3, 2, 1, 1, 2, 1, 0, 0, 0, 1, 1, 1, 0, 1, 3, 1, 1, 2, 2, 2,
       2, 1, 2, 3, 0, 2, 0, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 2, 0,
       1, 0, 2, 2, 0, 2, 0, 0, 0, 1, 1, 1, 0, 2, 0, 3, 1, 0, 0, 1, 0, 0,
       3, 1, 3, 2, 0, 2, 2, 2, 3, 0, 1, 1, 1, 3, 0, 2, 1, 0, 2, 1, 3, 2,
       1, 1, 0, 2, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 2, 1, 2, 1, 2,
       1, 1, 0, 3, 0, 1, 2, 0, 2, 2, 2, 2, 0, 2, 1, 1, 2, 2, 1, 1, 1, 2,
       1, 0, 2, 1, 1, 2, 0, 1, 1, 3, 3, 2, 1, 2, 0, 2, 1, 2, 1, 0, 0, 1,
       2, 0, 2, 2, 1, 2, 1, 1, 2, 3, 0, 1, 2, 3, 2, 0, 3, 3, 2, 3, 0, 0,
       2, 3, 2, 0, 2, 3, 2, 3, 1, 2, 2, 1, 0, 0, 0, 1, 0, 2, 2, 0, 2, 2,
       1, 1, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 3, 2, 1, 1, 0, 2, 2, 3, 2, 1,
       2, 1, 1, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 1, 1, 2, 0, 0, 0, 3, 2, 0,
       1, 1, 1, 3, 0, 1, 0, 3, 3, 0, 2, 3, 2, 2, 1, 1, 0, 0, 2, 1, 3, 0,
       3, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 2, 1, 0, 0, 2, 3, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 0, 0, 1, 1, 1, 0, 3, 3, 2, 2, 0, 0, 2, 0, 2, 2,
       2, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 3, 3, 0, 2, 1, 2, 0, 0,
       1, 2, 1, 2, 2, 1, 3, 1, 1, 1, 2, 1, 1, 0, 1, 0, 0, 3, 2, 2, 2, 0,
       0, 2, 0, 0, 2, 2, 0, 2, 1, 0, 1, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 0,
       2, 0, 2, 3, 1, 2, 0, 1, 3, 2, 0, 2, 0, 1, 0, 0, 3, 0, 0, 2, 1, 0,
       0, 1, 2, 0, 0, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 2, 3, 2, 2, 0, 1, 1,
       0, 2, 3, 2, 3, 1, 0, 1, 2, 1, 3, 0, 2, 2, 3, 0, 2, 0, 0, 1, 1, 0,
       0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 3, 0, 1, 0, 1, 2, 1, 1, 2, 1, 0, 1,
       0, 0, 0, 1, 0, 2, 2, 0, 0, 1, 3, 0, 1, 2, 1, 1, 3, 2, 1, 2, 2, 3,
       2, 2, 3, 1, 3, 0, 0, 2, 0, 2, 0, 2, 1, 1, 1, 3, 0, 1, 0, 1, 2, 1,
       2, 2, 2, 0, 0, 0, 1, 3, 2, 0, 2, 2, 0, 0, 2, 1, 0, 1, 1, 2, 3, 3,
       2, 1, 2, 2, 2, 0, 2, 0, 2, 0, 1, 3, 0, 0, 0, 3, 1, 2, 0, 0, 2, 2,
       0, 1, 3, 1, 0, 2, 0, 3, 0, 2, 2, 1, 0, 3, 0, 2, 0, 2, 3, 2, 1, 0,
       1, 1, 0, 1, 0, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 1, 2, 3,
       3, 1, 1, 1, 3, 0, 0, 3, 2, 1, 1, 0, 0, 2, 2, 2, 0, 1, 0, 3, 1, 3,
       1, 2, 2, 2, 1, 1, 3, 0, 3, 3, 1, 2, 2, 0, 1, 2, 2, 2, 0, 3, 2, 2,
       1, 0, 3, 0, 2, 2, 3, 2, 2, 1, 2, 1, 0, 0, 1, 2, 0, 2, 0, 2, 2, 2,
       3, 1, 0, 2, 1, 1, 2, 2, 2, 3, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       3, 0, 2, 0, 0, 1, 0, 1, 1, 1, 0, 2, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1,
       3, 0, 0, 2, 2, 1, 1, 1, 0, 0, 2, 1, 2, 2, 0, 1, 2, 0, 1, 1, 1, 0,
       3, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 2, 1, 1, 1, 0, 1, 3, 0, 3, 1,
       0, 0, 2, 2, 0, 1, 2, 0, 1, 2, 1, 0, 3, 1, 1, 2, 0, 0, 0, 2, 0, 3,
       0, 2, 2, 0, 1, 2, 2, 0, 0, 3, 0, 0, 1, 2, 2, 0, 2, 0, 0, 1, 1, 3,
       3, 2, 1, 0, 2, 1, 2, 0, 1, 2, 0, 2, 3, 0, 0, 2, 1, 1, 0, 0, 0, 2,
       0, 0, 3, 0, 2, 3, 3, 3, 0, 1])

In [16]:
dataset['le_Property_Area'] = la.transform(dataset['Property_Area'])
dataset.head(23)

,Load_ID,Name,Gender,Married,Dependent,Education,Self_Employed,Application_No,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,le_Property_Area
0,LP100000,Applicant_0,Male,Yes,1,Not Graduate,No,APP1000,6392.0,7598.0,394.0,180.0,1.0,Urban,Y,2
1,LP100001,Applicant_1,Male,Yes,3+,Graduate,Yes,APP1001,10690.0,NaN,329.0,240.0,0.0,Rural,Y,0
2,LP100002,Applicant_2,Female,Yes,1,Graduate,Yes,APP1002,2521.0,2271.0,118.0,360.0,NaN,Rural,N,0
3,LP100003,Applicant_3,Male,Yes,1,NaN,Yes,APP1003,12613.0,14322.0,630.0,360.0,NaN,Urban,Y,2
4,LP100004,Applicant_4,Male,No,2,Not Graduate,No,APP1004,13795.0,NaN,593.0,NaN,NaN,NaN,N,3
5,LP100005,Applicant_5,Male,Yes,NaN,Not Graduate,Yes,APP1005,22029.0,6641.0,536.0,360.0,0.0,Rural,NaN,0
6,LP100006,Applicant_6,Male,Yes,3+,Graduate,Yes,APP1006,NaN,3030.0,487.0,120.0,0.0,Urban,N,2
7,LP100007,Applicant_7,Male,Yes,0,Not Graduate,Yes,APP1007,6938.0,12941.0,264.0,NaN,1.0,Urban,N,2
8,LP100008,Applicant_8,Female,Yes,NaN,NaN,No,APP1008,20209.0,14279.0,405.0,180.0,0.0,Rural,Y,0
9,LP100009,Applicant_9,Male,NaN,3+,Not Graduate,No,APP1009,21347.0,6068.0,128.0,240.0,0.0,Rural,N,0
10,LP100010,Applicant_10,NaN,Yes,1,Graduate,Yes,APP1010,14265.0,NaN,359.0,360.0,1.0,Semiurban,N,1
11,LP100011,Applicant_11,Male,Yes,3+,Graduate,Yes,APP1011,7640.0,7607.0,566.0,120.0,1.0,Urban,Y,2
12,LP100012,Applicant_12,Male,No,1,Graduate,No,APP1012,21003.0,11532.0,357.0,240.0,1.0,Rural,N,0
13,LP100013,Applicant_13,Male,Yes,2,Not Graduate,NaN,APP1013,5328.0,10377.0,493.0,360.0,1.0,Rural,N,0
14,LP100014,Applicant_14,Male,Yes,NaN,NaN,NaN,APP1014,11601.0,22.0,602.0,240.0,0.0,Rural,Y,0
15,LP100015,Applicant_15,Male,No,2,Graduate,Yes,APP1015,24610.0,14096.0,370.0,360.0,1.0,Semiurban,Y,1
16,LP100016,Applicant_16,Female,Yes,0,Not Graduate,No,APP1016,11805.0,10277.0,254.0,120.0,NaN,Semiurban,N,1
17,LP100017,Applicant_17,Male,Yes,3+,Not Graduate,No,APP1017,24760.0,1158.0,474.0,240.0,NaN,NaN,N,3
18,LP100018,Applicant_18,Female,No,2,Not Graduate,Yes,APP1018,2536.0,6305.0,461.0,180.0,1.0,Urban,N,2
19,LP100019,Applicant_19,Female,Yes,0,Not Graduate,Yes,APP1019,10396.0,14638.0,307.0,240.0,0.0,Urban,N,2
20,LP100020,Applicant_20,Male,Yes,1,Graduate,No,APP1020,15061.0,11317.0,689.0,360.0,1.0,Urban,N,2
21,LP100021,Applicant_21,Male,Yes,0,Graduate,Yes,APP1021,4344.0,5454.0,577.0,NaN,0.0,NaN,N,3
22,LP100022,Applicant_22,Female,Yes,2,Graduate,No,APP1022,NaN,NaN,514.0,240.0,1.0,Urban,NaN,2